title = "FairCopy Learn@DLF Workshop"
baseURL = "https://faircopy-learndlf.netlify.app"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "ananke-resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 50
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "FairCopy Learn@DLF Workshop"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "A Hugo site for publishing TEI encoded texts."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
